# Generated by Django 3.2.9 on 2021-11-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='hall', max_length=50, verbose_name='movie'),
            preserve_default=False,
        ),
    ]
