# Generated by Django 3.2.9 on 2021-11-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
    ]
